# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 320)
        MainWindow.setMinimumSize(QtCore.QSize(480, 320))
        MainWindow.setMaximumSize(QtCore.QSize(480, 320))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        MainWindow.setFont(font)
        MainWindow.setWindowTitle("")
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Feeding = QtWidgets.QPushButton(self.centralwidget)
        self.Feeding.setGeometry(QtCore.QRect(50, 40, 371, 51))
        self.Feeding.setObjectName("Feeding")
        self.Weight = QtWidgets.QPushButton(self.centralwidget)
        self.Weight.setGeometry(QtCore.QRect(50, 120, 371, 51))
        self.Weight.setObjectName("Weight")
        self.Development = QtWidgets.QPushButton(self.centralwidget)
        self.Development.setGeometry(QtCore.QRect(50, 200, 371, 51))
        self.Development.setObjectName("Development")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.Feeding.setText(_translate("MainWindow", "Feeding"))
        self.Weight.setText(_translate("MainWindow", "Caloric Intake"))
        self.Development.setText(_translate("MainWindow", "Development"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
